# Generated by Django 3.1.1 on 2020-11-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
